### ISSUE TITLE
Generate The GraphQL Schema

### ISSUE THREAD

**Issue by the-vampiire** [chingu-x/chingu-api#41]

**Comment by TheSabby** [comment]
enum _OrderFormat {
    ASC
    DESC
  }

  type User {
    id: ID!
    firstName: String!
    cohorts: [Cohort!]!
  }

  type Cohort {
    title: String!
    group: Group!
  }

  type Thread {
    id: ID!,
    title: String!,
    memberCount: Int!,
    asdf: String!
  }

  type Query {
    threads(size: Int = 10, lastId: Int = 0, order: _OrderFormat): [Thread!]!
    thread(threadId: ID!): Thread
    comments(threadId: ID!, size: Int = 10, lastId: Int = 0, order: _OrderFormat): [Comment!]!
    user: User!
  }

  type Mutation {
    createThread(title: String!): Thread
    deleteThread(threadId: ID!): Thread
    createComment(threadId: ID!, body: String!): Comment
    deleteComment(commentId: ID!): Comment
    createUser(firstName: String!, lastName: String!, email: String!, password: String!): User
    signinUser(email: String!, password: String!): String
  }
